const menu = [
    {
      id: 1,
      title: 'Chemex',
      category: 'Hot Drinks',
      price: 2.000,
      img: './images/Chemex.jpg',
      desc: `Stylish pour-over coffee maker which produce clean, smooth coffee `,
    },
    {
      id: 2,
      title: 'ICED Chemex',
      category: 'Cold Drinks',
      price: 2.000,
      img: './images/Iced-chemex.jpg',
      desc: `Cold-brewed coffee made using the Chemex pour-over method. `,
    },
    {
      id: 3,
      title: 'Mix berry mojito',
      category: 'Non Coffee',
      price: 1.850,
      img: './images/mix-berry-mojito.jpg',
      desc: `Refreshing, fruity twist on the classic mojito. It combines muddled fresh berries.`,
    },
    {
      id: 4,
      title: 'Cheesecake',
      category: 'Cakes',
      price: 2.000,
      img: './images/Cheesecake.jpg',
      desc: `Creamy dessert made with a smooth filling of cream cheese. `,
    },
    {
      id: 5,
      title: 'Latte',
      category: 'Hot Drinks',
      price: 2.000,
      img: './images/latte.jpg',
      desc: `Creamy espresso drink made with steamed milk and a touch of foam. `,
    },
    {
      id: 6,
      title: 'Flat white',
      category: 'Hot Drinks',
      price: 1.500,
      img: './images/Flatwhite.jpg',
      desc: `Velvety espresso drink made with a double shot of espresso and steamed milk, topped with a thin layer of microfoam. `,
    },
    {
      id: 7,
      title: 'Cappuccino',
      category: 'Hot Drinks',
      price: 2.000,
      img: './images/Cappuccino.jpg',
      desc: `Balanced espresso-based drink with equal parts espresso, steamed milk, and milk foam. `,
    },
    {
      id: 8,
      title: 'Cortado',
      category: 'Hot Drinks',
      price: 1.5,
      img: './images/Cortado.jpg',
      desc: `Espresso drink with equal parts espresso and steamed milk. `,
    },
    {
      id: 9,
      title: 'boutique latte',
      category: 'Hot Drinks',
      price: 2.000,
      img: './images/boutique-latte.jpg',
      desc: `Espresso base, a blend of regular and sweetened condensed milk. `,
    },
    {
      id: 10,
      title: 'Americano',
      category: 'Hot Drinks',
      price: 1.5,
      img: './images/Americano.jpg',
      desc: `simple espresso-based drink made by diluting a shot of espresso with hot water. `,
    },
    {
      id: 11,
      title: 'Double Espresso',
      category: 'Hot Drinks',
      price: 1.5,
      img: './images/DoubleEspresso.jpg',
      desc: `Iconcentrated shot of coffee made with twice the amount of ground coffee. `,
    },
    {
      id: 12,
      title: ' Dark Mocha',
      category: 'Hot Drinks',
      price: 2.000,
      img: './images/HotDarkMocha.jpg',
      desc: `Made with espresso, steamed milk, and dark chocolate syrup. `,
    },
    {
      id: 13,
      title: ' White Mocha',
      category: 'Hot Drinks',
      price: 1.5,
      img: './images/HotWhiteMocha.jpg',
      desc: `Made with espresso, steamed milk, and white chocolate syrup. `,
    },
    {
      id: 14,
      title: 'Turkish coffee',
      category: 'Hot Drinks',
      price: 1.750,
      img: './images/Turkishcoffee.jpg',
      desc: `Made by boiling finely ground coffee with water. `,
    },
    {
      id: 15,
      title: ' V60 ',
      category: 'Hot Drinks',
      price: 2.000,
      img: './images/Americano.jpg',
      desc: ` Smooth, well-balanced cup of coffee. Top Pick `,
    },
    {
      id: 16,
      title: 'Ice Dark Mocha',
      category: 'Cold Drinks',
      price: 2.000,
      img: './images/Icedarkmocha.jpg',
      desc: `Made with espresso, chilled milk, and dark chocolate syrup, served over ice. `,
    },
    {
      id: 17,
      title: 'Ice White Mocha',
      category: 'Cold Drinks',
      price: 2.000,
      img: './images/Icedwhitemocha.jpg',
      desc: `Made with espresso, white chocolate syrup, and milk, served over ice. `,
    },
    {
      id: 18,
      title: 'Iced V60',
      category: 'Cold Drinks',
      price: 1.750,
      img: './images/HotV60.jpg',
      desc: `Pour-over coffee brewed using the V60 method, but served over ice. `,
    },
    {
      id: 19,
      title: 'Iced Americano',
      category: 'Cold Drinks',
      price: 2.000,
      img: './images/IceAmericano.jpg',
      desc: ` Made by diluting espresso with cold water and ice.`,
    },
    {
      id: 20,
      title: 'Cold brew',
      category: 'Cold Drinks',
      price: 2.000,
      img: './images/Coldbrew.jpg',
      desc: `Highly concentrated coffee brewed slowly with cold water over an extended period (usually 12-24 hours). It results in a rich.`,
    },
    {
      id: 21,
      title: 'Iced Latte',
      category: 'Cold Drinks',
      price: 2.000,
      img: './images/latte.jpg',
      desc: `Made with chilled milk and ice, offering a smooth, balanced flavor.`,
    },
    {
      id: 22,
      title: 'Iced boutique latte',
      category: 'Cold Drinks',
      price: 2.000,
      img: './images/latte.jpg',
      desc: `Espresso base, a blend of regular and sweetened condensed milk, served over ice. `,
    },
    {
      id: 23,
      title: 'Iced carmel shaken',
      category: 'Cold Drinks',
      price: 2.000,
      img: './images/Caramelshaken.jpg',
      desc: `Made by shaking espresso, milk, and caramel syrup with ice, creating a frothy, sweet beverage. `,
    },
    {
      id: 24,
      title: 'Iced vanilla shaken',
      category: 'Cold Drinks',
      price: 2.000,
      img: './images/Vanillaiceshaken.jpg',
      desc: `Made by shaking espresso, milk, and vanilla syrup with ice. `,
    },
    {
      id: 25,
      title: ' Matcha',
      category: 'Cold Drinks',
      price: 2.000,
      img: './images/Matcha.jpg',
      desc: `Finely ground, powdered green tea known for its vibrant color and earthy flavor. When mixed with milk (hot or iced). `,
    },
    {
      id: 26,
      title: ' Blue berry mojito',
      category: 'Non Coffee',
      price: 1.850,
      img: './images/blueberrymojito.jpg',
      desc: `Made with muddled fresh blueberries, mint leaves, lime juice, and a splash of soda water.`,
    },
    {
      id: 27,
      title: ' strawberry mojito',
      category: 'Non Coffee',
      price: 1.850,
      img: './images/strawberrymojiti.jpg',
      desc: `Made with muddled fresh strawberries, mint leaves, lime juice, and soda water. `,
    },
    {
      id: 28,
      title: ' Lemonade',
      category: 'Cold Drinks',
      price: 1.500,
      img: './images/lemonade.jpg',
      desc: `Made from freshly squeezed lemon juice, water, and sweetener. `,
    },
    {
      id: 29,
      title: ' Green tea with mint',
      category: 'Non Coffee',
      price: 1.100,
      img: './images/Greentea.jpg',
      desc: `Made by infusing green tea with fresh mint leaves. `,
    },
    {
      id: 30,
      title: ' Black Tea',
      category: 'Non Coffee',
      price: 1.100,
      img: './images/Blacktea.jpg',
      desc: ` An intense aromatic taste Classic, energizing option for tea lovers. `,
    },
    {
      id: 31,
      title: ' Water',
      category: 'Non Coffee',
      price: 0.500,
      img: './images/water.jpg',
      desc: `Water that epitomizes elegance, Mineral water 500 ml.`,
    },
    {
      id: 32,
      title: 'Banana cake',
      category: 'Cakes',
      price: 0.800,
      img: './images/Bananacake.jpg',
      desc: `Flavorful cake made with ripe bananas, creating a naturally sweet and soft texture. `,
    },
    {
      id: 33,
      title: 'Apple Pie Bites',
      category: 'Cakes',
      price: 0.500,
      img: './images/ApplePieBites.jpg',
      desc: `Mini, bite-sized versions of the classic apple pie, featuring a flaky, buttery crust filled with spiced, sweetened apples. `,
    },
    {
      id: 34,
      title: ' Dates Cake',
      category: 'Cakes',
      price: 1.750,
      img: './images/DatesCake.jpg',
      desc: `Deep flavor of the dates combined with the buttery caramel creates a luxurious, indulgent treat.`,
    },
    {
      id: 35,
      title: ' chocolate cake',
      category: 'Cakes',
      price: 2.250,
      img: './images/choclatecake.jpg',
      desc: `Rich and moist cake made with cocoa or melted chocolate. `,
    },
    {
      id: 36,
      title: ' Ghariba',
      category: 'Cakes',
      price: 10.,
      img: './images/Ghariba.jpg',
      desc: `Elevate Your Sweet Experience, Melt-in-your-mouth texture. `,
    },
    {
      id: 37,
      title: ' Crème brulee',
      category: 'Cakes',
      price: 1.500,
      img: './images/Cream.jpg',
      desc: `Classic French dessert consisting of a rich custard base made from cream. `,
    },
  ];
  export default menu;
  